name: Execute Win64

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
    - "docs/**"
    - "README.md"
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "res/**"
      - "appimage/**"
      - "flatpak/**"

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/lib-flutter-build-win-64.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
